KPPatients/Models/CreateRole.cs
using System.ComponentModel.DataAnnotations;

namespace KPPatients.Models
{
    public class CreateRole
    {
        [Required]
        public string RoleName { get; set; }
    }
}

KPPatients/Models/EditRole.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace KPPatients.Models
{
    public class EditRole
    {
        public EditRole()
        {
            Users = new List<string>();
        }

        public string Id { get; set; }

        [Required(ErrorMessage = "Role name is required")]
        public string RoleName { get; set; }

        public List<string> Users { get; set; }
    }
}

KPPatients/Models/UserRole.cs
namespace KPPatients.Models
{
    public class UserRole
    {
        public string UserId { get; set; }

        public string UserName { get; set; }

        public string RoleId { get; set; }
    }
}

KPPatients/Controllers/KPRoleController.cs
using KPPatients.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace KPPatients.Controllers
{
    public class KPRoleController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly RoleManager<IdentityRole> roleManager;

        public KPRoleController(UserManager<IdentityUser> userManger, RoleManager<IdentityRole> roleManger)
        {
            this.userManager = userManger;
            this.roleManager = roleManger;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult CreateRole()
        {
            return View();
        }

        public IActionResult RoleList()
        {
            var roleList = roleManager.Roles;
            ViewBag.RoleList = roleList;
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> CreateRole(CreateRole model)
        {

            if (ModelState.IsValid)
            {
                var isRole = roleManager.FindByNameAsync(model.RoleName);

                if (isRole.Result != null)
                {
                    TempData["message"] = "Role is aleady exists.";
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    try
                    {
                        IdentityRole role = new IdentityRole { Name = model.RoleName };

                        var result = await roleManager.CreateAsync(role);

                        if (result.Succeeded)
                        {
                            TempData["message"] = "Role added: " + model.RoleName;
                            return RedirectToAction(nameof(RoleList));
                        }

                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError("", error.Description);
                        }
                    }
                    catch (Exception ex)
                    {
                        TempData["message"] = ex.GetBaseException().Message.ToString();
                        ModelState.AddModelError("", ex.GetBaseException().Message.ToString());
                    }

                }
            }
            return RedirectToAction(nameof(RoleList));

        }

        public async Task<IActionResult> Delete(string id)
        {
            var role = await roleManager.FindByIdAsync(id);
            if (role == null)
            {
                TempData["message"] = "Role is not exists.";
            }

            var model = new EditRole
            {
                Id = role.Id,
                RoleName = role.Name
            };

            foreach (var user in userManager.Users)
            {
                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    model.Users.Add(user.UserName);
                }
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(EditRole model)
        {
            var role = await roleManager.FindByIdAsync(model.Id);
            if (role == null)
            {
                TempData["message"] = "Role is not exists.";
            }
            else
            {
                try
                {

                    role.Name = model.RoleName;

                    TempData["message"] = "Role deleted: " + role.Name;
                    var result = await roleManager.DeleteAsync(role);

                    if (result.Succeeded)
                    {
                        return RedirectToAction("RoleList");
                    }
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }

                }
                catch (Exception ex)
                {
                    TempData["message"] = ex.GetBaseException().Message.ToString();
                    ModelState.AddModelError("", ex.GetBaseException().Message.ToString());
                }
            }

            return View(model);
        }

        public async Task<IActionResult> UserRole(string RoleId)
        {
            var role = await roleManager.FindByIdAsync(RoleId);
            //ViewBag.RoleName = role.Name;
            ViewBag.RoleId = RoleId;

            var model = new List<UserRole>();
            var dropdownModel = new List<UserRole>();

            foreach (var user in userManager.Users)
            {

                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    var userrole = new UserRole
                    {
                        UserId = user.Id,
                        UserName = user.UserName
                    };


                    model.Add(userrole);
                }

                var userroles = new UserRole
                {
                    UserId = user.Id,
                    UserName = user.UserName
                };

                dropdownModel.Add(userroles);

            }


            ViewData["Users"] = new SelectList(dropdownModel.OrderBy(x => x.UserName), "UserId", "UserName");
            ;
            ViewBag.UsersRole = model;



            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddUserRole(UserRole model)
        {
            var role = await roleManager.FindByIdAsync(model.RoleId);
            if (role == null)
            {
                // Error meesage
                ViewBag.ErrorMessage = $"Role not found";
                TempData["message"] = $"Role not found";
            }

            try
            {
                var userDetail = await userManager.FindByIdAsync(model.UserId);
                IdentityResult result = null;
                if (!(await userManager.IsInRoleAsync(userDetail, role.Name)))
                {
                    result = await userManager.AddToRoleAsync(userDetail, role.Name);
                    TempData["message"] = "User added in role: " + role.Name;
                }
            }
            catch (Exception ex)
            {
                TempData["message"] = ex.GetBaseException().Message.ToString();
                ModelState.AddModelError("", ex.GetBaseException().Message.ToString());
            }
            return RedirectToAction("UserRole", new { RoleId = model.RoleId });
        }

        public async Task<IActionResult> RemoveUserRole(string RoleId, string UserId)
        {
            var role = await roleManager.FindByIdAsync(RoleId);
            if (role == null)
            {
                // Error meesage
                ViewBag.ErrorMessage = $"Role not found";
                TempData["message"] = $"Role not found";
            }
            else
            {
                try
                {
                    var userDetail = await userManager.FindByIdAsync(UserId);
                    IdentityResult result = null;

                    if (await userManager.IsInRoleAsync(userDetail, role.Name))
                    {
                        result = await userManager.RemoveFromRoleAsync(userDetail, role.Name);
                        TempData["message"] = "User removed from role: " + role.Name;
                    }
                }
                catch (Exception ex)
                {
                    TempData["message"] = ex.GetBaseException().Message.ToString();
                    ModelState.AddModelError("", ex.GetBaseException().Message.ToString());
                }
            }

            return RedirectToAction("UserRole", new { RoleId = RoleId });
        }

    }
}

KPPatients/Views/KPRole/CreateRole.cshtml
@model CreateRole
@{
    ViewData["Title"] = "CreateRole";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>CreateRole</h1>
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <h4> Create Role</h4>
            <hr />
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RoleName"></label>
                <input asp-for="RoleName" class="form-control" />
                <span asp-validation-for="RoleName" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">Create Role</button>
        </form>
    </div>

</div>

@if (ViewBag.RoleList != null)
{
    <form method="post" asp-action="CreateRole">
        <hr />
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="RoleName"></label>
            <input asp-for="RoleName" class="form-control" />
            <span asp-validation-for="RoleName" class="text-danger"></span>

        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Create Role</button>
        </div>
    </form>

    <table class="table">
        <thead>
            <tr>
                <th>
                    Role
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var role in ViewBag.RoleList)
            {
                <tr>
                    <td>
                        @role.Name
                    </td>

                    <td>
                        <a asp-controller="KPRole" asp-action="UserRole" asp-route-RoleId="@role.Id">Users Role</a> |

                        @if (role.Name.ToLower() != "administrators")
                        {
                            <a asp-controller="KPRole" asp-action="Delete" asp-route-id="@role.Id">Delete Role</a>
                        }
                    </td>
                </tr>
            }
    </table>
}

KPPatients/Views/KPRole/Delete.cshtml
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Role</h4>
    <hr />
    <dl class="row">
        @*<dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RoleName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RoleName)
        </dd>*@
    </dl>

    <h2>Users In Role</h2>
    <div>
        <ul>
            @foreach (var user in Model.Users)
            {
                <li>
                    @user

                </li>
            }
        </ul>
    </div>

    <form asp-action="Delete">@*
        <input type="hidden" asp-for="Id" />*@

        <input type="submit" value="Delete" class="btn btn-danger" />|

        <a asp-controller="KPRole" asp-action="RoleList">Return to Role List</a>
    </form>
</div>

KPPatients/Views/KPRole/EditRole.cshtml
@model EditRole
@{
    ViewData["Title"] = "EditRole";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>EditRole</h1>

<form method="post">
    <div class="form-group row">
        <label asp-for="Id" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Id" disabled class="form-control" />
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="RoleName" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="RoleName" class="form-control" />
            <span asp-validation-for="RoleName" class="text-danger"></span>
        </div>
    </div>
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Submit</button>
            <a asp-action="ListRole" class="btn btn-primary">Cancel</a>
        </div>
    </div>
    <div class="card">
        <div class="card-header"><h3>Users in this role</h3></div>
        <div class="card-body">
            @if (Model.Users.Any())
            {
                foreach (var user in Model.Users)
                {
                    <h5 class="card-title">@user</h5>
                }
            }
            else
            {
                <h5 class="card-title">None at the moment</h5>
            }

        </div>
        <div class="card-footer">
            <a asp-controller="KPRole" asp-action="EditUsersInRole" asp-route-roleId="@Model.Id"
               class="btn btn-primary">Add or Remove Users</a>
        </div>
    </div>
</form>

KPPatients/Views/KPRole/EditUsersInRole.cshtml
@model List<UserRole>
@{
    var roleId = ViewBag.roleId;
    ViewData["Title"] = "Edit Users In Role";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>EditUsersInRole</h1>

<form method="post">
    <div class="card">
        <div class="card-header">
            <h2>Add or remove Users from this role.</h2>
        </div>
        <div class="card-body">
            @for (int i = 0; i < Model.Count; i++)
            {
                    <input type="hidden" asp-for="@Model[i].UserId" />
                    <div class="form-check m-1">@*
                        <input asp-for="@Model[i].IsSelected" class="form-check-input" />*@
                        <label class="form-check-label">@Model[i].UserName</label>
                    </div>
            }
        </div>
        <div class="card-footer">
            <input type="submit" value="Update" class="btn btn-primary" />
            <a asp-action="EditRole" asp-route-id="@roleId" class="btn btn-primary">Cancel</a>
        </div>
    </div>
</form>

KPPatients/Views/KPRole/RoleList.cshtml
@{
    ViewData["Title"] = "RoleList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>RoleList</h1>
@if (ViewBag.RoleList != null)
{
    <a class="btn btn-primary" asp-controller="KPRole" asp-action="CreateRole">Add Role</a>
        <form method="post" asp-action="CreateRole">
            <hr />

        </form>


        <table class="table">
            <thead>
                <tr>
                    <th>
                        Role
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            @foreach (var role in ViewBag.RoleList)
            {
                        <tr>
                            <td>
                        @role.Name
                            </td>

                            <td>
                                <a asp-controller="KPRole" asp-action="UserRole" asp-route-RoleId="@role.Id">Users Role</a> |

                        @if (role.Name.ToLower() != "administrators")
                        {
                                        <a asp-controller="KPRole" asp-action="Delete" asp-route-id="@role.Id">Delete Role</a>
                        }
                            </td>
                        </tr>
            }
        </table>
}

KPPatients/Views/KPRole/UserRole.cshtml
@{
    ViewData["Title"] = "UserRole";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>UserRole</h1>
@if (ViewData["Users"] != null)
{

        <form method="post" asp-action="AddUserRole">
            <div asp-validation-summary="All" class="text-danger"></div>
            @*<input type="hidden" value="@ViewBag.RoleId" asp-for="RoleId" />
            <div class="form-group">
                <label>Users:</label>
                <select asp-for="UserId" class="form-control" asp-items="ViewBag.Users"></select>
            </div>
            *@<div class="form-group">
                <button type="submit" class="btn btn-primary">Add to Role</button>
            </div>
        </form>

        <table class="table">
            <thead>
                <tr>
                    <th>
                        Username
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            @foreach (var user in ViewBag.UsersRole)
            {
                        <tr>
                            <td>
                        @user.UserName
                            </td>

                    @*@if (SignInManager.IsSignedIn(User))
                    {
                        if (user.UserName != User.Identity.Name && ViewBag.RoleName.ToLower() != "administrators")
                        {
                                            <td>
                                                <a asp-controller="KPRole" asp-action="RemoveUserRole" asp-route-RoleId="@ViewBag.RoleId" asp-route-UserId="@user.UserId">Remove</a>
                                            </td>
                        }
                    }
*@
                        </tr>
            }
        </table>

        <a asp-controller="KPRole" asp-action="RoleList">Return to Role List</a>
}